name: Run Bot 24/7

on:
  schedule:
    - cron: "0 */5 * * *"  # Restart otomatis setiap 5 jam
  workflow_dispatch:       # Bisa dijalankan manual

concurrency:
  group: bot-24-7
  cancel-in-progress: true  # Jika workflow baru mulai, workflow lama akan dihentikan otomatis

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Hindari masalah otorisasi GitHub Actions

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Gunakan versi terbaru

      - name: Debug File & Path
        run: |
          echo "📂 Cek isi repository:"
          ls -la
          echo "✅ File yang tersedia telah dicek."

      - name: Install Dependencies
        run: |
          echo "📦 Memulai instalasi dependencies..."
          npm install
          echo "✅ Instalasi dependencies selesai."

      - name: Jalankan Bot
        run: |
          echo "🚀 Menjalankan index.js..."
          nohup node index.js > output.log 2>&1 &  # Jalankan di background
          tail -f output.log  # Menampilkan log agar tidak dianggap idle
