name: Run Bot 24/7

on:
  schedule:
    - cron: "0 */3 * * *"  # Restart otomatis setiap 3 jam
  workflow_dispatch:       # Bisa dijalankan manual

jobs:
  cleanup_old_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install gh -y

      - name: Delete Duplicates & Completed Workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Gunakan token bawaan GitHub
          REPO: ${{ github.repository }}
        run: |
          echo "Fetching all workflow runs..."
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          runs=$(gh api repos/$REPO/actions/runs --paginate --jq '.workflow_runs | map({id: .id, status: .status})')

          in_progress_runs=$(echo "$runs" | jq -r 'map(select(.status == "in_progress" or .status == "queued")) | .[].id')

          if [ -n "$in_progress_runs" ]; then
            latest_run=$(echo "$in_progress_runs" | head -n 1)
            echo "Keeping latest running workflow: $latest_run"

            for run_id in $in_progress_runs; do
              if [ "$run_id" != "$latest_run" ]; then
                echo "Deleting duplicate running workflow: $run_id"
                gh api -X DELETE repos/$REPO/actions/runs/$run_id
              fi
            done
          fi

          completed_runs=$(echo "$runs" | jq -r 'map(select(.status != "in_progress" and .status != "queued")) | .[].id')

          for run_id in $completed_runs; do
            echo "Deleting completed workflow: $run_id"
            gh api -X DELETE repos/$REPO/actions/runs/$run_id
          done

  run-bot:
    needs: cleanup_old_workflows  # Pastikan hapus workflow lama dulu sebelum jalankan bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Hindari masalah otorisasi GitHub Actions

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Gunakan versi terbaru

      - name: Debug File & Path
        run: |
          echo "📂 Cek isi repository:"
          ls -la
          echo "✅ File yang tersedia telah dicek."

      - name: Install Dependencies
        run: |
          echo "📦 Memulai instalasi dependencies..."
          npm install
          echo "✅ Instalasi dependencies selesai."

      - name: Jalankan Bot
        run: |
          echo "🚀 Menjalankan index.js..."
          nohup node index.js > output.log 2>&1 &  # Jalankan di background
          tail -f output.log  # Menampilkan log agar tidak dianggap idle
