name: Run Bot 24/7

on:
  schedule:
    - cron: "*/59 * * * *"  # Restart setiap 59 menit agar tetap berjalan
  workflow_dispatch:       # Bisa dijalankan manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Hindari masalah otorisasi GitHub Actions

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Gunakan versi terbaru

      - name: Debug File & Path
        run: |
          echo "📂 Cek isi repository:"
          ls -la
          echo "✅ File yang tersedia telah dicek."

      - name: Install Dependencies
        run: |
          echo "📦 Memulai instalasi dependencies..."
          npm install
          npm install -g pm2  # Install pm2 untuk menjaga bot tetap berjalan
          echo "✅ Instalasi dependencies selesai."

      - name: Jalankan Bot atau Server
        run: |
          echo "🚀 Menjalankan index.js dengan pm2..."
          pm2 start index.js --name bot
          pm2 save
          echo "✅ Bot berjalan dengan pm2."

      - name: Simpan Status PM2
        run: pm2 list
